import Head from 'next/head';
// import Image from 'next/image';
import { useState } from 'react';
import Navbar from '../components/Navbar';

import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from 'react-icons/ai';

export default function Home() {
  const [open, setOpen] = useState(true);

  return (
    <>
      <Head>
        <link href="css/hover-min.css" rel="stylesheet" />
        <link rel="stylesheet" href="wickedcss.min.css" />

        <title>Javier-Cervera-Lopez</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="grid grid-flow-col gap-6 w-full bg-neutral-900   ">
          <Navbar />
          {/* right main */}
          <div className="flex flex-col md:flex-row   items-center">
            <div className=" p-2 m-10 ">
              <h2 className="text-6xl py-2  font-bold text-red-500 md:text-7xl font-coms">
                Javier Cervera
              </h2>
              <h3 className="text-2xl py-2 font-medium text-neutral-900 md:text-3xl dark:text-stone-100 font-com">
                Frontend Developer
              </h3>
              <p className=" dark:text-stone-100 text-md mx-auto pt-2 leading-5  font-light text-stone-700 md:text-lg max-w-xl ">
                Freelancer providing Web Services with the latest technolgies
              </p>
              <p className="text-md dark:text-stone-100 mx-auto text-neutral-900 font-light lg max-w-xl ">
                Contact me for any further inquires.
              </p>

              {/* ICONS */}
              <div className=" text-5xl flex justify-center gap-10 text-blue-500 mt-20 ">
                <AiFillTwitterCircle
                  data-aos="zoom-out-up"
                  data-aos-duration="1000"
                  data-aos-offset="1500"
                />
                <AiFillLinkedin
                  data-aos="zoom-out-up"
                  data-aos-duration="1500"
                  data-aos-offset="1500"
                />
                <AiFillGithub
                  data-aos="zoom-out-up"
                  data-aos-duration="2000"
                  data-aos-offset="1500"
                />
              </div>
              {/* ICON */}
            </div>
          </div>

          {/* end right main */}
        </section>
      </main>
    </>
  );
}
